import React from "react";

function Home() {
  return (
    <>
      <Head>
        <title>
          Paylio - Money Transfer and Online Payments React Next JS Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          href="/images/favicon.ico"
          type="image/x-icon"
        />
      </Head>

      <main>

      </main>
    </>
  );
}

export default Home;
