import React from "react";
import Head from "next/head";
import Banner from "@/components/Banner";
import Features from "@/components/Features";
import About from "@/components/About";
import Payment from "@/components/Payment";
import HowWorks from "@/components/HowWorks";
import AppDownload from "@/components/AppDownload";
import Testimonial from "@/components/Testimonial";
import Faq from "@/components/Faq";

function Home() {
  return (
    <>
      <Head>
        <title>
          Paylio - Money Transfer and Online Payments React Next JS Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          href="/images/favicon.ico"
          type="image/x-icon"
        />
      </Head>

      <main>
        <Banner />
        <Features/>
        <About/>
        <Payment/>
        <HowWorks/>
        <AppDownload/>
        <Testimonial/>
        <Faq/>
      </main>
    </>
  );
}

export default Home;
